version: "3"
services:
 poxa:
  image: edgurgel/poxa-automated
  env_file: .env
  ports:
   - 8080:8080
   - 8443:8443
  volumes:
#   - ./poxa.conf:/app/poxa/running-config/poxa.conf
   - ./ssl_certs:/ssl_certs
